[Sonder-LunarLayout607375206Snap]
Meter=Image
ImageName=#@#Presets\Preset\Snap\Sonder - Lunar Layout.png
MaskImageName=#@#Presets\presetmask.png
W=340
X=(15-#Scroll#)
Y=100
LeftMouseUpAction=[!SetVariable Name "Sonder - Lunar Layout"][!Update][!Delay 1000][!CommandMeasure Script "ApplyPreset('Sonder - Lunar Layout')"]
DynamicVariables=1
Group=Preset
[Sonder-LunarLayout607375206]
Meter=String
Text=Sonder - Lunar Layout
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=160
[Sonder-LunarLayout607375206Time]
Meter=String
Text=2020 Sep 12 16:15:09
MeterStyle=TimeStyle
X=r
Y=R
[Sonder-LunarLayout607375206Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=200
LeftMouseUpAction=[!SetVariable Name "Sonder - Lunar Layout"][!Update][!Delay 1000][!CommandMeasure Script "DeletePreset('Sonder - Lunar Layout')"]
[SonderLayout405349672Snap]
Meter=Image
ImageName=#@#Presets\Preset\Snap\Sonder Layout.png
MaskImageName=#@#Presets\presetmask.png
W=340
X=(15-#Scroll#)
Y=235
LeftMouseUpAction=[!SetVariable Name "Sonder Layout"][!Update][!Delay 1000][!CommandMeasure Script "ApplyPreset('Sonder Layout')"]
DynamicVariables=1
Group=Preset
[SonderLayout405349672]
Meter=String
Text=Sonder Layout
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=295
[SonderLayout405349672Time]
Meter=String
Text=2020 Sep 12 16:09:08
MeterStyle=TimeStyle
X=r
Y=R
[SonderLayout405349672Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=335
LeftMouseUpAction=[!SetVariable Name "Sonder Layout"][!Update][!Delay 1000][!CommandMeasure Script "DeletePreset('Sonder Layout')"]
