[Sonder-LunarLayout1147556980Snap]
Meter=Image
ImageName=#@#Presets\Preset\Snap\Sonder - Lunar Layout.png
MaskImageName=#@#Presets\presetmask.png
W=340
X=(15-#Scroll#)
Y=100
LeftMouseUpAction=[!WriteKeyValue Variables CurrentTheme "Sonder - Lunar Layout" "#@#Variables.inc"][!CommandMeasure MeasureRunCopyVariablesFile Run][!SetOption ApplyingPreset Text "Applying Preset..."][!ShowMeter ApplyingPreset][!Redraw][!SetVariable Name "Sonder - Lunar Layout"][!Update][!Delay 1000][!CommandMeasure Script "ApplyPreset('Sonder - Lunar Layout')"]
DynamicVariables=1
Group=Preset
[Sonder-LunarLayout1147556980]
Meter=String
Text=Sonder - Lunar Layout
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=160
[Sonder-LunarLayout1147556980Time]
Meter=String
Text=2021 Jun 04 10:00:22
MeterStyle=TimeStyle
X=r
Y=R
[Sonder-LunarLayout1147556980Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=200
LeftMouseUpAction=[!SetVariable Name "Sonder - Lunar Layout"][!Update][!Delay 1000][!CommandMeasure Script "DeletePreset('Sonder - Lunar Layout')"]
[SonderLayout1119321639Snap]
Meter=Image
ImageName=#@#Presets\Preset\Snap\Sonder Layout.png
MaskImageName=#@#Presets\presetmask.png
W=340
X=(15-#Scroll#)
Y=235
LeftMouseUpAction=[!WriteKeyValue Variables CurrentTheme "Sonder Layout" "#@#Variables.inc"][!CommandMeasure MeasureRunCopyVariablesFile Run][!SetOption ApplyingPreset Text "Applying Preset..."][!ShowMeter ApplyingPreset][!Redraw][!SetVariable Name "Sonder Layout"][!Update][!Delay 1000][!CommandMeasure Script "ApplyPreset('Sonder Layout')"]
DynamicVariables=1
Group=Preset
[SonderLayout1119321639]
Meter=String
Text=Sonder Layout
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=295
[SonderLayout1119321639Time]
Meter=String
Text=2021 Jun 04 09:02:42
MeterStyle=TimeStyle
X=r
Y=R
[SonderLayout1119321639Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=335
LeftMouseUpAction=[!SetVariable Name "Sonder Layout"][!Update][!Delay 1000][!CommandMeasure Script "DeletePreset('Sonder Layout')"]
