[Sonder-LunarLayout1521220Snap]
Meter=Image
ImageName=#@#Presets\Preset\Snap\Sonder - Lunar Layout.png
MaskImageName=#@#Presets\presetmask.png
W=340
X=(15-#Scroll#)
Y=100
LeftMouseUpAction=[!WriteKeyValue Variables CurrentTheme "Sonder - Lunar Layout" "#@#Variables.inc"][!CommandMeasure MeasureRunCopyVariablesFile Run][!SetOption ApplyingPreset Text "Applying Preset..."][!ShowMeter ApplyingPreset][!Redraw][!SetVariable Name "Sonder - Lunar Layout"][!Update][!Delay 1000][!CommandMeasure Script "ApplyPreset('Sonder - Lunar Layout')"]
DynamicVariables=1
Group=Preset
[Sonder-LunarLayout1521220]
Meter=String
Text=Sonder - Lunar Layout
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=160
[Sonder-LunarLayout1521220Time]
Meter=String
Text=2020 Oct 14 11:54:18
MeterStyle=TimeStyle
X=r
Y=R
[Sonder-LunarLayout1521220Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=200
LeftMouseUpAction=[!SetVariable Name "Sonder - Lunar Layout"][!Update][!Delay 1000][!CommandMeasure Script "DeletePreset('Sonder - Lunar Layout')"]
[SonderLayout685180082Snap]
Meter=Image
ImageName=#@#Presets\Preset\Snap\Sonder Layout.png
MaskImageName=#@#Presets\presetmask.png
W=340
X=(15-#Scroll#)
Y=235
LeftMouseUpAction=[!WriteKeyValue Variables CurrentTheme "Sonder Layout" "#@#Variables.inc"][!CommandMeasure MeasureRunCopyVariablesFile Run][!SetOption ApplyingPreset Text "Applying Preset..."][!ShowMeter ApplyingPreset][!Redraw][!SetVariable Name "Sonder Layout"][!Update][!Delay 1000][!CommandMeasure Script "ApplyPreset('Sonder Layout')"]
DynamicVariables=1
Group=Preset
[SonderLayout685180082]
Meter=String
Text=Sonder Layout
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=295
[SonderLayout685180082Time]
Meter=String
Text=2020 Oct 14 10:29:50
MeterStyle=TimeStyle
X=r
Y=R
[SonderLayout685180082Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=335
LeftMouseUpAction=[!SetVariable Name "Sonder Layout"][!Update][!Delay 1000][!CommandMeasure Script "DeletePreset('Sonder Layout')"]
[PERSONAL-SonderTransform235010052Snap]
Meter=Image
ImageName=#@#Presets\Preset\Snap\PERSONAL-Sonder Transform.png
MaskImageName=#@#Presets\presetmask.png
W=340
X=(15-#Scroll#)
Y=370
LeftMouseUpAction=[!WriteKeyValue Variables CurrentTheme "PERSONAL-Sonder Transform" "#@#Variables.inc"][!CommandMeasure MeasureRunCopyVariablesFile Run][!SetOption ApplyingPreset Text "Applying Preset..."][!ShowMeter ApplyingPreset][!Redraw][!SetVariable Name "PERSONAL-Sonder Transform"][!Update][!Delay 1000][!CommandMeasure Script "ApplyPreset('PERSONAL-Sonder Transform')"]
DynamicVariables=1
Group=Preset
[PERSONAL-SonderTransform235010052]
Meter=String
Text=PERSONAL-Sonder Transform
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=430
[PERSONAL-SonderTransform235010052Time]
Meter=String
Text=2020 Sep 25 17:12:59
MeterStyle=TimeStyle
X=r
Y=R
[PERSONAL-SonderTransform235010052Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=470
LeftMouseUpAction=[!SetVariable Name "PERSONAL-Sonder Transform"][!Update][!Delay 1000][!CommandMeasure Script "DeletePreset('PERSONAL-Sonder Transform')"]
[PERSONAL-Lunar983228037Snap]
Meter=Image
ImageName=#@#Presets\Preset\Snap\PERSONAL-Lunar.png
MaskImageName=#@#Presets\presetmask.png
W=340
X=(375-#Scroll#)
Y=100
LeftMouseUpAction=[!WriteKeyValue Variables CurrentTheme "PERSONAL-Lunar" "#@#Variables.inc"][!CommandMeasure MeasureRunCopyVariablesFile Run][!SetOption ApplyingPreset Text "Applying Preset..."][!ShowMeter ApplyingPreset][!Redraw][!SetVariable Name "PERSONAL-Lunar"][!Update][!Delay 1000][!CommandMeasure Script "ApplyPreset('PERSONAL-Lunar')"]
DynamicVariables=1
Group=Preset
[PERSONAL-Lunar983228037]
Meter=String
Text=PERSONAL-Lunar
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=160
[PERSONAL-Lunar983228037Time]
Meter=String
Text=2020 Oct 02 06:56:21
MeterStyle=TimeStyle
X=r
Y=R
[PERSONAL-Lunar983228037Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=200
LeftMouseUpAction=[!SetVariable Name "PERSONAL-Lunar"][!Update][!Delay 1000][!CommandMeasure Script "DeletePreset('PERSONAL-Lunar')"]
