[Sonder-LunarLayout1044262382Snap]
Meter=Image
ImageName=#SETTINGSPATH#Presets\Themes\Snap\Sonder - Lunar Layout.png
MaskImageName=#@#Presets\presetmask.png
W=340
X=(15-#Scroll#)
Y=100
LeftMouseUpAction=[!WriteKeyValue Variables CurrentTheme "Sonder - Lunar Layout" "#@#Variables.inc"][!CommandMeasure MeasureRunCopyVariablesFile Run][!SetOption ApplyingPreset Text "Applying Preset..."][!ShowMeter ApplyingPreset][!Redraw][!SetVariable Name "Sonder - Lunar Layout"][!Update][!Delay 1000][!CommandMeasure Script "ApplyPreset('Sonder - Lunar Layout')"]
DynamicVariables=1
Group=Preset
[Sonder-LunarLayout1044262382]
Meter=String
Text=Sonder - Lunar Layout
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=160
[Sonder-LunarLayout1044262382Time]
Meter=String
Text=2021 Aug 10 10:19:52
MeterStyle=TimeStyle
X=r
Y=R
[Sonder-LunarLayout1044262382Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=200
LeftMouseUpAction=[!SetVariable Name "Sonder - Lunar Layout"][!Update][!Delay 1000][!CommandMeasure Script "DeletePreset('Sonder - Lunar Layout')"]
[SonderLayout863793658Snap]
Meter=Image
ImageName=#SETTINGSPATH#Presets\Themes\Snap\Sonder Layout.png
MaskImageName=#@#Presets\presetmask.png
W=340
X=(15-#Scroll#)
Y=235
LeftMouseUpAction=[!WriteKeyValue Variables CurrentTheme "Sonder Layout" "#@#Variables.inc"][!CommandMeasure MeasureRunCopyVariablesFile Run][!SetOption ApplyingPreset Text "Applying Preset..."][!ShowMeter ApplyingPreset][!Redraw][!SetVariable Name "Sonder Layout"][!Update][!Delay 1000][!CommandMeasure Script "ApplyPreset('Sonder Layout')"]
DynamicVariables=1
Group=Preset
[SonderLayout863793658]
Meter=String
Text=Sonder Layout
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=295
[SonderLayout863793658Time]
Meter=String
Text=2021 Aug 10 10:02:32
MeterStyle=TimeStyle
X=r
Y=R
[SonderLayout863793658Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=335
LeftMouseUpAction=[!SetVariable Name "Sonder Layout"][!Update][!Delay 1000][!CommandMeasure Script "DeletePreset('Sonder Layout')"]
