[Lunar1521220Snap]
Meter=Image
ImageName=#SETTINGSPATH#Presets\Visualizers\Snap\Lunar.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Lunar')"]
DynamicVariables=1
Group=Preset
[Lunar1521220]
Meter=String
Text=Lunar
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=140
[Lunar1521220Time]
Meter=String
Text=2020 Aug 13 15:04:43
MeterStyle=TimeStyle
X=r
Y=R
[Lunar1521220Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Lunar')"]
[TealExplosion685180082Snap]
Meter=Image
ImageName=#SETTINGSPATH#Presets\Visualizers\Snap\Teal Explosion.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=215
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Teal Explosion')"]
DynamicVariables=1
Group=Preset
[TealExplosion685180082]
Meter=String
Text=Teal Explosion
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=275
[TealExplosion685180082Time]
Meter=String
Text=2017 Jun 21 20:09:17
MeterStyle=TimeStyle
X=r
Y=R
[TealExplosion685180082Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=315
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Teal Explosion')"]
[SummonRitual235010052Snap]
Meter=Image
ImageName=#SETTINGSPATH#Presets\Visualizers\Snap\Summon Ritual.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=350
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Summon Ritual')"]
DynamicVariables=1
Group=Preset
[SummonRitual235010052]
Meter=String
Text=Summon Ritual
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=410
[SummonRitual235010052Time]
Meter=String
Text=2017 Jun 21 21:09:10
MeterStyle=TimeStyle
X=r
Y=R
[SummonRitual235010052Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=450
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Summon Ritual')"]
[SonderDefault983228037Snap]
Meter=Image
ImageName=#SETTINGSPATH#Presets\Visualizers\Snap\Sonder Default.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Sonder Default')"]
DynamicVariables=1
Group=Preset
[SonderDefault983228037]
Meter=String
Text=Sonder Default
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=140
[SonderDefault983228037Time]
Meter=String
Text=2020 Aug 05 18:47:45
MeterStyle=TimeStyle
X=r
Y=R
[SonderDefault983228037Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Sonder Default')"]
[RetroMonstercat711226349Snap]
Meter=Image
ImageName=#SETTINGSPATH#Presets\Visualizers\Snap\Retro Monstercat.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=215
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Retro Monstercat')"]
DynamicVariables=1
Group=Preset
[RetroMonstercat711226349]
Meter=String
Text=Retro Monstercat
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=275
[RetroMonstercat711226349Time]
Meter=String
Text=2017 Jun 21 21:02:04
MeterStyle=TimeStyle
X=r
Y=R
[RetroMonstercat711226349Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=315
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Retro Monstercat')"]
[PurpleSea583406704Snap]
Meter=Image
ImageName=#SETTINGSPATH#Presets\Visualizers\Snap\Purple Sea.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=350
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Purple Sea')"]
DynamicVariables=1
Group=Preset
[PurpleSea583406704]
Meter=String
Text=Purple Sea
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=410
[PurpleSea583406704Time]
Meter=String
Text=2017 Jun 21 19:57:59
MeterStyle=TimeStyle
X=r
Y=R
[PurpleSea583406704Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=450
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Purple Sea')"]
[PinkyLittleStar425867600Snap]
Meter=Image
ImageName=#SETTINGSPATH#Presets\Visualizers\Snap\Pinky Little Star.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(735-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Pinky Little Star')"]
DynamicVariables=1
Group=Preset
[PinkyLittleStar425867600]
Meter=String
Text=Pinky Little Star
MeterStyle=PresetStyle
X=(740-#Scroll#)
Y=140
[PinkyLittleStar425867600Time]
Meter=String
Text=2017 Jun 21 20:26:18
MeterStyle=TimeStyle
X=r
Y=R
[PinkyLittleStar425867600Delete]
Meter=String
MeterStyle=DeleteStyle
X=(1070-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Pinky Little Star')"]
