[Rainmeter]
LocalFontFace="#@#Fonts\ITCAvantGardePro-XLt.ttf"
LocalFontFace2="#@#Fonts\ITCAvantGardePro-Bk.ttf"
LocalFontFace3="#@#Fonts\Montserrat-Bold.otf"
LocalFontFace4="#@#Fonts\Montserrat-Light.otf"
LocalFontFace5="#@#Fonts\Montserrat-Regular.otf"
LocalFontFace6="#@#Fonts\Montserrat-SemiBold.otf"
LocalFontFace7="#@#Fonts\News Gothic Condensed.ttf"
;LocalFontFace8= Segou UI
LocalFontFace9="#@#Fonts\OpenSans-Light.ttf"
LocalFontFace10="#@#Fonts\Glacial Indifference.otf"
LocalFontFace11="#@#Fonts\Gobold Bold.otf"
LocalFontFace12="#@#Fonts\Porter.otf"
LocalFontFace13="#@#Fonts\Tuesday Night.otf"
;LocalFontFace14=Trebuchet MS
LocalFontFace15="#@#Fonts\Emmylou Signature Normal.ttf"
LocalFontFace16="#@#Fonts\Montserrat Light.ttf"
LocalFontFace17="#@#Fonts\Montserrat"