[SonderDefault17994928Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Sonder Default.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Sonder Default')"]
DynamicVariables=1
Group=Preset
[SonderDefault17994928]
Meter=String
Text=Sonder Default
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=140
[SonderDefault17994928Time]
Meter=String
Text=2020 Aug 05 18:47:45
MeterStyle=TimeStyle
X=r
Y=R
[SonderDefault17994928Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Sonder Default')"]
[Lunar866131143Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Lunar.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=215
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Lunar')"]
DynamicVariables=1
Group=Preset
[Lunar866131143]
Meter=String
Text=Lunar
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=275
[Lunar866131143Time]
Meter=String
Text=2020 Aug 13 15:04:43
MeterStyle=TimeStyle
X=r
Y=R
[Lunar866131143Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=315
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Lunar')"]
[PinkyLittleStar489053915Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Pinky Little Star.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=350
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Pinky Little Star')"]
DynamicVariables=1
Group=Preset
[PinkyLittleStar489053915]
Meter=String
Text=Pinky Little Star
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=410
[PinkyLittleStar489053915Time]
Meter=String
Text=2017 Jun 21 20:26:18
MeterStyle=TimeStyle
X=r
Y=R
[PinkyLittleStar489053915Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=450
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Pinky Little Star')"]
[PurpleSea662324668Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Purple Sea.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Purple Sea')"]
DynamicVariables=1
Group=Preset
[PurpleSea662324668]
Meter=String
Text=Purple Sea
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=140
[PurpleSea662324668Time]
Meter=String
Text=2017 Jun 21 19:57:59
MeterStyle=TimeStyle
X=r
Y=R
[PurpleSea662324668Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Purple Sea')"]
[RetroMonstercat365723727Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Retro Monstercat.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=215
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Retro Monstercat')"]
DynamicVariables=1
Group=Preset
[RetroMonstercat365723727]
Meter=String
Text=Retro Monstercat
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=275
[RetroMonstercat365723727Time]
Meter=String
Text=2017 Jun 21 21:02:04
MeterStyle=TimeStyle
X=r
Y=R
[RetroMonstercat365723727Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=315
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Retro Monstercat')"]
[SummonRitual635202415Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Summon Ritual.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=350
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Summon Ritual')"]
DynamicVariables=1
Group=Preset
[SummonRitual635202415]
Meter=String
Text=Summon Ritual
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=410
[SummonRitual635202415Time]
Meter=String
Text=2017 Jun 21 21:09:10
MeterStyle=TimeStyle
X=r
Y=R
[SummonRitual635202415Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=450
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Summon Ritual')"]
[TealExplosion931914665Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Teal Explosion.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(735-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Teal Explosion')"]
DynamicVariables=1
Group=Preset
[TealExplosion931914665]
Meter=String
Text=Teal Explosion
MeterStyle=PresetStyle
X=(740-#Scroll#)
Y=140
[TealExplosion931914665Time]
Meter=String
Text=2017 Jun 21 20:09:17
MeterStyle=TimeStyle
X=r
Y=R
[TealExplosion931914665Delete]
Meter=String
MeterStyle=DeleteStyle
X=(1070-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Teal Explosion')"]
