[SonderDefault27827208Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Sonder Default.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Sonder Default')"]
DynamicVariables=1
Group=Preset
[SonderDefault27827208]
Meter=String
Text=Sonder Default
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=140
[SonderDefault27827208Time]
Meter=String
Text=2020 Aug 05 18:47:45
MeterStyle=TimeStyle
X=r
Y=R
[SonderDefault27827208Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Sonder Default')"]
[Lunar935179724Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Lunar.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=215
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Lunar')"]
DynamicVariables=1
Group=Preset
[Lunar935179724]
Meter=String
Text=Lunar
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=275
[Lunar935179724Time]
Meter=String
Text=2020 Aug 13 15:04:43
MeterStyle=TimeStyle
X=r
Y=R
[Lunar935179724Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=315
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Lunar')"]
[PinkyLittleStar184587150Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Pinky Little Star.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=350
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Pinky Little Star')"]
DynamicVariables=1
Group=Preset
[PinkyLittleStar184587150]
Meter=String
Text=Pinky Little Star
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=410
[PinkyLittleStar184587150Time]
Meter=String
Text=2017 Jun 21 20:26:18
MeterStyle=TimeStyle
X=r
Y=R
[PinkyLittleStar184587150Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=450
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Pinky Little Star')"]
[PurpleSea57101432Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Purple Sea.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Purple Sea')"]
DynamicVariables=1
Group=Preset
[PurpleSea57101432]
Meter=String
Text=Purple Sea
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=140
[PurpleSea57101432Time]
Meter=String
Text=2017 Jun 21 19:57:59
MeterStyle=TimeStyle
X=r
Y=R
[PurpleSea57101432Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Purple Sea')"]
[RetroMonstercat11242192Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Retro Monstercat.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=215
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Retro Monstercat')"]
DynamicVariables=1
Group=Preset
[RetroMonstercat11242192]
Meter=String
Text=Retro Monstercat
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=275
[RetroMonstercat11242192Time]
Meter=String
Text=2017 Jun 21 21:02:04
MeterStyle=TimeStyle
X=r
Y=R
[RetroMonstercat11242192Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=315
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Retro Monstercat')"]
[SummonRitual423789835Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Summon Ritual.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=350
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Summon Ritual')"]
DynamicVariables=1
Group=Preset
[SummonRitual423789835]
Meter=String
Text=Summon Ritual
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=410
[SummonRitual423789835Time]
Meter=String
Text=2017 Jun 21 21:09:10
MeterStyle=TimeStyle
X=r
Y=R
[SummonRitual423789835Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=450
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Summon Ritual')"]
[TealExplosion782797929Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Teal Explosion.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(735-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Teal Explosion')"]
DynamicVariables=1
Group=Preset
[TealExplosion782797929]
Meter=String
Text=Teal Explosion
MeterStyle=PresetStyle
X=(740-#Scroll#)
Y=140
[TealExplosion782797929Time]
Meter=String
Text=2017 Jun 21 20:09:17
MeterStyle=TimeStyle
X=r
Y=R
[TealExplosion782797929Delete]
Meter=String
MeterStyle=DeleteStyle
X=(1070-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Teal Explosion')"]
