[Lunar150934779Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Lunar.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Lunar')"]
DynamicVariables=1
Group=Preset
[Lunar150934779]
Meter=String
Text=Lunar
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=140
[Lunar150934779Time]
Meter=String
Text=2020 Aug 13 15:04:43
MeterStyle=TimeStyle
X=r
Y=R
[Lunar150934779Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Lunar')"]
[SonderDefault7902927Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Sonder Default.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=215
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Sonder Default')"]
DynamicVariables=1
Group=Preset
[SonderDefault7902927]
Meter=String
Text=Sonder Default
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=275
[SonderDefault7902927Time]
Meter=String
Text=2020 Aug 05 18:47:45
MeterStyle=TimeStyle
X=r
Y=R
[SonderDefault7902927Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=315
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Sonder Default')"]
[PinkyLittleStar473470678Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Pinky Little Star.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(15-#Scroll#)
Y=350
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Pinky Little Star')"]
DynamicVariables=1
Group=Preset
[PinkyLittleStar473470678]
Meter=String
Text=Pinky Little Star
MeterStyle=PresetStyle
X=(20-#Scroll#)
Y=410
[PinkyLittleStar473470678Time]
Meter=String
Text=2017 Jun 21 20:26:18
MeterStyle=TimeStyle
X=r
Y=R
[PinkyLittleStar473470678Delete]
Meter=String
MeterStyle=DeleteStyle
X=(350-#Scroll#)
Y=450
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Pinky Little Star')"]
[PurpleSea324947590Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Purple Sea.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Purple Sea')"]
DynamicVariables=1
Group=Preset
[PurpleSea324947590]
Meter=String
Text=Purple Sea
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=140
[PurpleSea324947590Time]
Meter=String
Text=2017 Jun 21 19:57:59
MeterStyle=TimeStyle
X=r
Y=R
[PurpleSea324947590Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Purple Sea')"]
[RetroMonstercat855445495Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Retro Monstercat.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=215
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Retro Monstercat')"]
DynamicVariables=1
Group=Preset
[RetroMonstercat855445495]
Meter=String
Text=Retro Monstercat
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=275
[RetroMonstercat855445495Time]
Meter=String
Text=2017 Jun 21 21:02:04
MeterStyle=TimeStyle
X=r
Y=R
[RetroMonstercat855445495Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=315
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Retro Monstercat')"]
[SummonRitual286323425Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Summon Ritual.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(375-#Scroll#)
Y=350
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Summon Ritual')"]
DynamicVariables=1
Group=Preset
[SummonRitual286323425]
Meter=String
Text=Summon Ritual
MeterStyle=PresetStyle
X=(380-#Scroll#)
Y=410
[SummonRitual286323425Time]
Meter=String
Text=2017 Jun 21 21:09:10
MeterStyle=TimeStyle
X=r
Y=R
[SummonRitual286323425Delete]
Meter=String
MeterStyle=DeleteStyle
X=(710-#Scroll#)
Y=450
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Summon Ritual')"]
[TealExplosion566710379Snap]
Meter=Image
ImageName=#@#Visualizer\Preset\Snap\Teal Explosion.png
MaskImageName=#@#Visualizer\presetmask.png
W=340
X=(735-#Scroll#)
Y=80
LeftMouseUpAction=[!CommandMeasure Script "ApplyPreset('Teal Explosion')"]
DynamicVariables=1
Group=Preset
[TealExplosion566710379]
Meter=String
Text=Teal Explosion
MeterStyle=PresetStyle
X=(740-#Scroll#)
Y=140
[TealExplosion566710379Time]
Meter=String
Text=2017 Jun 21 20:09:17
MeterStyle=TimeStyle
X=r
Y=R
[TealExplosion566710379Delete]
Meter=String
MeterStyle=DeleteStyle
X=(1070-#Scroll#)
Y=180
LeftMouseUpAction=[!CommandMeasure Script "DeletePreset('Teal Explosion')"]
