[Variables]
LocalFontFace=ITC Avant Garde Pro XLt
LocalFontFace2=ITC Avant Garde Pro Bk
FontFace3=Segou UI
Color1=255,255,255,204
Color2=0,0,0,20
Color3=105,155,115
Color4=255,255,255,204
Hours=%I
fc=f
January=jan
February=feb
March=march
April=april
May=may
June=june
July=july
August=aug
September=sep
October=oct
November=nov
December=dec
Monday=mon
Tuesday=tue
Wednesday=wed
Thursday=thu
Friday=fri
Saturday=sat
Sunday=sun
Monday2=monday
Tuesday2=tuesday
Wednesday2=wednesday
Thursday2=thursday
Friday2=friday
Saturday2=saturday
Sunday2=sunday

ClockScale=1
DateScale=1

GlobalSkinBackgroundColor=Black
GlobalSkinBackgroundAlpha=110
GlobalSkinBackgroundAlphaInactive=1

ScaleValueRecycleBin=1
RecycleBinColor=255,255,255
RecycleBinTextColor=255,255,255,160

ScaleValueSystem=1
Systembarheight=1
SystemcolorBar=105,155,115
SystemcolorText=210,210,210
ShowSystemGPU=1
ShowSystemTemp=1
ShowSystemSwap=0

ScaleValueNetwork=1
SidebarWidthNetwork=200
NetworkDownColor=255,255,255,160
NetworkUpColor=105,155,115,200
NetworkMainTextColor=255,255,255

ShowClockSettingsIcon=1
Settingsiconpath=#@#Images\colors2.png
