[time1]
StringAlign=Center
StringCase=None
StringStyle=Normal
StringEffect=None
FontEffectColor=#color2#
FontColor=#color1#
FontFace=#LocalFontFace#
FontSize=(#ClockScale#*150)
AntiAlias=1
ClipString=0

[time2]
StringAlign=Center
StringCase=None
StringStyle=Normal
StringEffect=None
FontEffectColor=#color2#
FontColor=#color3#
FontFace=#LocalFontFace#
FontSize=(#ClockScale#*150)
AntiAlias=1
ClipString=0

[timeshadow]
StringAlign=Center
StringStyle=Normal
FontColor=#color2#
FontFace=#LocalFontFace#
FontSize=(#ClockScale#*150)
AntiAlias=1
ClipString=0

;-------------------------------

[Date1]
StringAlign=Center
StringCase=None
StringStyle=Normal
StringEffect=shadow
FontEffectColor=#color2#
FontColor=#color4#
FontFace=#LocalFontFace#
FontSize=(#DateScale#*25)
AntiAlias=1
ClipString=0

;-------------------------------

; [Sys1]
; StringAlign=right
; StringCase=None
; StringStyle=Normal
; StringEffect=shadow
; FontEffectColor=#color2#
; FontColor=#color1#
; FontFace=#LocalFontFace2#
; FontSize=9
; AntiAlias=1
; ClipString=0

; [Sys2]
; StringAlign=left
; StringCase=None
; StringStyle=Normal
; StringEffect=shadow
; FontEffectColor=#color2#
; FontColor=#color1#
; FontFace=#LocalFontFace2#
; FontSize=9
; AntiAlias=1
; ClipString=0